repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
